<a href="https://colab.research.google.com/github/JOSEPHREDDY07/Ineuron_ml_deployment_trng/blob/master/Assignment%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#assignment 3
#1 try catch
def divz(a,b):
  try:
    print(" the result is :", a // b)
  except ZeroDivisionError:
    print(" divide by zero error")
divz(3,1)



 the result is : 3


In [6]:
divz(9,0)

 divide by zero error


In [0]:
#2. list 

In [11]:
subjects = ["Americans ","Indians"]
verbs = ["play","watch"]
objects = ["Baseball","Cricket"]
for i in subjects:
  for j in verbs:
    for k in objects:
      print (i  + ' ' + j + ' ' + k)
  

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [16]:
# Vander matrix
import numpy as np
x = np.array([1, 2, 3, 5])
N = 3
print(np.column_stack([x**(N-1-i) for i in range(N)]))
print(np.vander(x, increasing=True))

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]


In [14]:
def vander(x,N):
  for i in range(N):
    np.column_stack([x**(N-1-i)

SyntaxError: ignored